### ISSUE TITLE
No server shows when one fails to update

### ISSUE THREAD

**Issue by Magesw** [tsebring/ArkBot#44]
I have noticed that when one of my servers fails to update then the website shows zero servers. Can we get this changed or is there something wrong and what is the cause of a server to fail to update?

Failed to update server (DFC Center)
[Update(D:\temp\6aa4560\ArkBot\Ark\ArkServerContext.cs:207)]

<Exception>
  <System.OverflowException>
    <Current />
    <Message>Value was either too large or too small for a UInt32.</Message>
    <TargetSite>UInt32 ToUInt32(Int32)</TargetSite>
    <Source>mscorlib</Source>
    <StackTrace><![CDATA[at System.Convert.ToUInt32(Int32 value)
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at ArkSavegameToolkitNet.IPropertyContainerExtensions.GetPropertyValue[TPropertyValue](IPropertyContainer self, ArkName name)
at ArkSavegameToolkitNet.Domain.ArkItem..ctor(IGameObject item, ISaveState saveState)
at ArkSavegameToolkitNet.Domain.IGameObjectExtensions.AsItem(IGameObject self, ISaveState saveState)
at ArkSavegameToolkitNet.Domain.ArkGameData.<>c__DisplayClass13_1.<Update>b__26(GameObject x)
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at ArkSavegameToolkitNet.Domain.ArkGameData.Update(CancellationToken ct, ArkPlayerExternal[] externalPlayerData, Boolean deferApplyNewData, ArkAnonymizeData anonymize)
at ArkBot.Ark.ArkServerContext.Update(Boolean manualUpdate, IConfig fullconfig, ISavegameBackupService savegameBackupService, IProgress`1 progress, CancellationToken ct)]]></StackTrace>
  </System.OverflowException>
</Exception>

**Comment by tsebring** [comment]
The current behavior with the server listing is not ideal and it should be improved in the future.

The error during update is always one of a thousand ways the data can be corrupt so it would not be possible to show a meaningful error.

Sadly the ARK server is not coded to work well with shared access to the save files. A simple file copy operation will potentially corrupt a save file if ARK decides it wants to write to the file at the same time something else is trying to read.

I've looked into ways to improve it and came to the conclusion that it is not currently possible. Not even shadow copying at the system level would help.

**Comment by Magesw** [comment]
Is it possible then to at least have it point to the file that is corrupted so it can be removed/replaced?

**Comment by tsebring** [comment]
Yes. That definitely needs to be logged somewhere. I hope to add it sometime, just stretched very thin right now.
